### ISSUE TITLE
Errors installing conan

### ISSUE THREAD

**Issue by w3r3wolv3s** [sergeyklay/pcloud-console-client#93]
Received a lot of errors when trying to run `pip3 install --user conan`.

This is a partial error output:
```
  ERROR: Failed building wheel for pluginbase
  Running setup.py clean for pluginbase
Failed to build conan future patch-ng pluginbase
Installing collected packages: urllib3, MarkupSafe, idna, charset-normalizer, certifi, tqdm, requests, PyYAML, python-dateutil, pygments, pluginbase, patch-ng, node-semver, Jinja2, future, fasteners, colorama, bottle, conan
  WARNING: The script normalizer is installed in '/home/werewolves/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script tqdm is installed in '/home/werewolves/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pygmentize is installed in '/home/werewolves/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
    Running setup.py install for pluginbase ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_euu9t9h/pluginbase_071c50e494294c978b4fbf86ab74fcd6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_euu9t9h/pluginbase_071c50e494294c978b4fbf86ab74fcd6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ajledgq1/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/werewolves/.local/include/python3.9/pluginbase
         cwd: /tmp/pip-install-_euu9t9h/pluginbase_071c50e494294c978b4fbf86ab74fcd6/
    Complete output (24 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib
    copying pluginbase.py -> build/lib
    running install_lib
    copying build/lib/pluginbase.py -> /home/werewolves/.local/lib/python3.9/site-packages
    byte-compiling /home/werewolves/.local/lib/python3.9/site-packages/pluginbase.py to pluginbase.cpython-39.pyc
    running install_egg_info
    running egg_info
    writing pluginbase.egg-info/PKG-INFO
    writing dependency_links to pluginbase.egg-info/dependency_links.txt
    writing top-level names to pluginbase.egg-info/top_level.txt
    reading manifest file 'pluginbase.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyo' found under directory 'tests'
    no previously-included directories found matching 'docs/_build'
    writing manifest file 'pluginbase.egg-info/SOURCES.txt'
    Copying pluginbase.egg-info to /home/werewolves/.local/lib/python3.9/site-packages/pluginbase-1.0.1.egg-info
    error: [Errno 13] Permission denied: '/home/werewolves/.local/lib/python3.9/site-packages/pluginbase-1.0.1.egg-info/PKG-INFO'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_euu9t9h/pluginbase_071c50e494294c978b4fbf86ab74fcd6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_euu9t9h/pluginbase_071c50e494294c978b4fbf86ab74fcd6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ajledgq1/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/werewolves/.local/include/python3.9/pluginbase Check the logs for full command output.

```

**Comment by w3r3wolv3s** [comment]
I was able to install **conan** using `sudo pip3 install --user conan`

It seemed to install everything in /root/.local, so I added /root/.local/bin to my PATH.

Now I am getting this error:
```
$ conan install . -if=build --build=missing
Traceback (most recent call last):
  File "/root/.local/bin/conan", line 5, in <module>
    from conans.conan import run
ModuleNotFoundError: No module named 'conans'
```
"conans" exists in `/root/.local/lib/python3.9/site-packages/conans/`
not sure how to reference that...

**Comment by w3r3wolv3s** [comment]
OK, was able to add `/root/.local/lib` to my PYTHONPATH. **conan** now runs, but I get this error:

`ERROR: [Errno 13] Permission denied: '/home/werewolves/.conan/data/gtest/cci.20210126/_/_/source/conandata.yml'`

File seems to be read only for "others". Changing permission doesn't help as when I re-run conan it cleans out the build directory and replaces the file.

**Comment by sergeyklay** [comment]
@w3r3wolv3s I'm not sure you should use `sudo` with `pip` (even more so when using `--user`). You only use `sudo` or elevated permissions when you want to install stuff for the global, system-wide Python installation. It's not safe and it's being frowned upon – see [What are the risks of running 'sudo pip'?](https://stackoverflow.com/q/21055859/95735) To install Python package in your home directory you don't need root privileges. See description of `--user` option to pip. I'd like to suggest removing conan, undo all changes in PATH and PYTHONLIB and going through the [standard installation flow](https://docs.conan.io/en/latest/installation.html).

**Comment by w3r3wolv3s** [comment]
@sergeyklay Unfortunately, as you can see from my first post, I was unable to install conan without using sudo. When I tried `pip3 install --user conan` from the instructions, I got a bunch of errors (example in the first post). I'm not entirely sure how to "remove conan" at this point. Sorry, I've never used pip or conan before.

**Comment by sergeyklay** [comment]
Could you please try the following:

```
$ sudo chown -R $USER $HOME/.local
$ sudo pip3 uninstall conan
$ pip3 install --user conan
```

**Comment by w3r3wolv3s** [comment]
Out of curiosity, I re-ran `pip3 install --user conan`
"Requirement already satisfied: conan in ./.local/lib/python3.9/site-packages (1.40.2)"

Should I try the next install step?

**Comment by sergeyklay** [comment]
Well, as I can see, you used the `root` user when for `pip3`. This is generally [bad](https://askubuntu.com/a/16179) [practice](https://superuser.com/a/666947/280737), even if you have clear reasons for doing so. Actually, to work with this repository, the root user is probably never needed. Could you please try with the regular user (and do not use sudo)? Anyway, could you verify conan is works now?

**Comment by w3r3wolv3s** [comment]
@sergeyklay I went ahead and uninstalled all of those components from the /root directory. I also made sure the /root directory was not in my PATH or PYTHONPATH.

I then attempted to install conan *without sudo* (`pip install conan` as they suggest on the conan page).

I verified that everything that did install went in my user folder `/home/werewolves/.local/lib/python3.9/site-packages/`

Unfortunately as before, installation of conan (at the "wheel" step) fails. The output and errors are here: [https://u.pcloud.link/publink/show?code=kZaU06XZGEhzM298XQVq6WrrvLAWiyPTpgkX](url)

**Comment by sergeyklay** [comment]
@w3r3wolv3s From logs you are provided (thank you!):

```
running egg_info
writing conan.egg-info/PKG-INFO
writing dependency_links to conan.egg-info/dependency_links.txt
writing entry points to conan.egg-info/entry_points.txt
writing requirements to conan.egg-info/requires.txt
writing top-level names to conan.egg-info/top_level.txt
reading manifest file 'conan.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'conan.egg-info/SOURCES.txt'
Copying conan.egg-info to build/bdist.linux-aarch64/wheel/conan-1.40.3.egg-info
error: [Errno 13] Permission denied: 'build/bdist.linux-aarch64/wheel/conan-1.40.3.egg-info/dependency_links.txt'
```

The key point is:
```
error: [Errno 13] Permission denied: 'build/bdist.linux-aarch64/wheel/conan-1.40.3.egg-info/dependency_links.txt'
```

You have to use `--user` option, as follows:

```
$ pip install --user conan
```

**Comment by w3r3wolv3s** [comment]
@sergeyklay OK, tried with --user flag. Similar result. Log files in the same location. out_user.txt and err_user.txt

**Comment by sergeyklay** [comment]
@w3r3wolv3s, This seems like a permissions issue in your environment for example see https://stackoverflow.com/a/43898861

Take a look at the logs:
```
...
Copying patch_ng.egg-info to build/bdist.linux-aarch64/wheel/patch_ng-1.17.4.egg-info
error: [Errno 13] Permission denied: 'build/bdist.linux-aarch64/wheel/patch_ng-1.17.4.egg-info/PKG-INFO'
...
```

Probably because you've already build package as `root` or using `sudo`. Try to clear your cache first:
```
$ sudo rm -rf /tmp/pip*
```

And then install conan as a regular user as follows:

```
$ pip install --user conan
```

**Comment by w3r3wolv3s** [comment]
No, that didn't work. And I removed all of the packages from root.he
out_user2.txt
err_user2.txt

This is the same thing that happened ***before*** I used sudo. That's why I tried sudo in the first place, because of the  permission issues. Sudo did allow everything to install, it just installed it in the root directory.

**Comment by sergeyklay** [comment]
Question: can you install any other package using pip? For example, could you install Pytest?
```
$ pip install pytest
```

**Comment by w3r3wolv3s** [comment]
Yes. That works fine. And as you can see from earlier logs *most* of the components from conan installed just fine. It just seems to die when it gets to "wheel for conan".

This is the ouptput:

werewolves@localhost:~$ pip install pytest
Collecting pytest
  Downloading pytest-6.2.5-py3-none-any.whl (280 kB)
     |████████████████████████████████| 280 kB 532 kB/s 
Collecting packaging
  Downloading packaging-21.0-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 2.1 MB/s 
Collecting py>=1.8.2
  Downloading py-1.10.0-py2.py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 1.3 MB/s 
Collecting pluggy<2.0,>=0.12
  Downloading pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting toml
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting attrs>=19.2.0
  Downloading attrs-21.2.0-py2.py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 1.2 MB/s 
Collecting iniconfig
  Downloading iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 761 kB/s 
Installing collected packages: pyparsing, toml, py, pluggy, packaging, iniconfig, attrs, pytest
Successfully installed attrs-21.2.0 iniconfig-1.1.1 packaging-21.0 pluggy-1.0.0 py-1.10.0 pyparsing-2.4.7 pytest-6.2.5 toml-0.10.2

**Comment by sergeyklay** [comment]
I'll rewrite the bootstraping process to drop Conan dependency

**Comment by w3r3wolv3s** [comment]
Great, just let me know when you are ready for me to try :)

**Comment by w3r3wolv3s** [comment]
@sergeyklay I am beginning to think this is just an issue with my system. Out of curiosity, I tried **rclone**. I had similar weird permission problems.

**Comment by w3r3wolv3s** [comment]
@sergeyklay this is definitely a problem with my system. I apologize for taking up your time.

**Comment by sergeyklay** [comment]
@w3r3wolv3s Don't worry. At least you pushed me to figure it out. In any case, the presence of conan dependency was hindered for many

**Comment by sergeyklay** [comment]
I got rid of сonan here https://github.com/sergeyklay/pcloud-console-client/pull/96
